# 科学计算模块numpy与绘图模块matplotlib基础

Y.Z. 2022.11.10 更新
相关链接:

* Python 科学计算基础 （整理）: https://blog.csdn.net/liang890319/article/details/52061351

* 用Python做科学计算: https://docs.huihoo.com/scipy/scipy-zh-cn/index.html

* 用Python做科学计算(链接丰富) https://zhuanlan.zhihu.com/Scientific-Computing

* # 与数组操作有关的模块快速入门-numpy

* random
* numpy,numpy.random
* pandas
* torch


## 产生随机数



In [1]:
import numpy as np
v = np.random.rand(10)
print('v=')
print(v)

v=
[0.75074834 0.58117286 0.74296301 0.78122893 0.4956058  0.3693099
 0.18765146 0.65493205 0.55559754 0.82649142]


In [2]:
# 使用numpy模块中的数组
import numpy as np
M = np.random.rand(2,5)
print('M=')
print(M)
print('M.shape dd')
print(M.shape)

M=
[[0.7092294  0.65510632 0.4231375  0.59477862 0.64945466]
 [0.20109658 0.6401718  0.62761572 0.95578684 0.65320921]]
M.shape dd
(2, 5)


### 创建数组

In [6]:
# 3x3的浮点型2维数组，并且初始化所有元素值为1
m1 = np.ones((3, 3), dtype=np.float64)
print('m1=')
print(m1)
# 2x2x3的无符号8位整型3维数组，并且初始化所有元素值为0
m2 = np.zeros((2, 3), dtype=np.uint8)
print('m2')
print(m2)
m3 = np.arange(10)      
print('m3=',m3)
m4 = np.linspace(0, 6, 7)# 等差数列
print('m4=',m4)
m5 = np.eye(6, dtype=np.float64)
print('m5=')
print(m5)

m1=
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
m2
[[0 0 0]
 [0 0 0]]
m3= [0 1 2 3 4 5 6 7 8 9]
m4= [0. 1. 2. 3. 4. 5. 6.]
m5=
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


## 常用统计函数示例

### 一维数组的统计操作

In [7]:
import numpy as np

a = [6, 4, 9, 7, 1, 8]    #
b = np.array(a)     # 根据列表转为numpy数组
print('type(b)=',type(b)) 

print('shape ',b.shape) 
print('argmax 最大值索引',b.argmax()) 
print('max    最大值',b.max())   
print('mean   平均值',b.mean() ) 

type(b)= <class 'numpy.ndarray'>
shape  (6,)
argmax 最大值索引 2
max    最大值 9
mean   平均值 5.833333333333333


### 二维数组的统计操作

In [8]:
c = [[3, 9,1,10], [7, 4,6,0],[8,3,5,9]]    # 二维列表
d = np.array(c)         # 二维numpy数组
print('d =')
print(d)
print('shape ',d.shape)           
print('size  ',d.size )          
print('argmax 每列最大值的行索引',d.argmax(axis=0)) 
print('argmax 每行最大值的列索引',d.argmax(axis=1)) 
print('max  每列最大值 ',d.max(axis=0))
print('max  每行最大值 ',d.max(axis=1))
print('mean 每列平均值',d.mean(axis=0))

d =
[[ 3  9  1 10]
 [ 7  4  6  0]
 [ 8  3  5  9]]
shape  (3, 4)
size   12
argmax 每列最大值的行索引 [2 0 1 0]
argmax 每行最大值的列索引 [3 0 3]
max  每列最大值  [ 8  9  6 10]
max  每行最大值  [10  7  9]
mean 每列平均值 [6.         5.33333333 4.         6.33333333]


In [9]:
d = np.array([[3, 9,1,10], [7, 4,6,0],[8,3,5,9]])         # 二维numpy数组
print('d =')
print(d)
print('每列求和:')
print(d.sum(axis=0))
print('每行求和:')
print(d.sum(axis=1))

d =
[[ 3  9  1 10]
 [ 7  4  6  0]
 [ 8  3  5  9]]
每列求和:
[18 16 12 19]
每行求和:
[23 17 25]



numpy中的ravel()、flatten()、squeeze()都有将多维数组转换为一维数组的功能：

* ravel()：如果没有必要，不会产生源数据的副本
* flatten()：返回源数据的副本
* squeeze()：只能对维数为1的维度降维
* reshape(-1)也可以“拉平”多维数组


In [10]:
c = [[3, 9,1,10], [7, 4,6,0],[8,3,5,9]]    # 二维列表
d = np.array(c)         # 二维numpy数组
r1 = d.flatten()             # 展开一个numpy数组为1维数组，array([1, 2, 3, 4])
r2 = np.ravel(d)             # 展开一个可以解析的结构为1维数组，array([1, 2, 3, 4])
print('flatten ')
print(r1)
#print('d=',d) # d不发生变化
print('ravel ')
print(r2)
#print('d=',d)# d不发生变化
r3 = d.reshape(-1)          
print('reshape ')
print(r3)


flatten 
[ 3  9  1 10  7  4  6  0  8  3  5  9]
ravel 
[ 3  9  1 10  7  4  6  0  8  3  5  9]
reshape 
[ 3  9  1 10  7  4  6  0  8  3  5  9]


In [11]:
v=[[3,5,2,9,7]]
r1 = np.squeeze(v)          
print('squeeze ')
print(r1)

v=[[3],[5],[2],[9],[7]]
r2 = np.squeeze(v)          
print('squeeze ')
print(r2)

squeeze 
[3 5 2 9 7]
squeeze 
[3 5 2 9 7]


## 数据的重复相关处理函数

In [12]:
# 创建一个一维数组，元素值是把3重复4次，array([3, 3, 3, 3])
import numpy as np
r1 = np.repeat(3, 4)
print('r1 ')
print(r1)
r2 = np.repeat([3], 4)
print('r2 ')
print(r2)
r3 = np.repeat([3,1,2], 4)
print('r3 ')
print(r3)

r1 
[3 3 3 3]
r2 
[3 3 3 3]
r3 
[3 3 3 3 1 1 1 1 2 2 2 2]


### tile类似于Matlab中的repmat函数

In [13]:
import numpy as np
r4 = np.repeat([3,1,2],(4))
print('r4 ')
print(r4)
r5 = np.tile([3,1,2],(1,4))
print('r5 ')
print(r5)
print('r5 type:',r5.shape)
r6= np.tile([3,1,2],(4,1))
print('r6 ')
print(r6)

r4 
[3 3 3 3 1 1 1 1 2 2 2 2]
r5 
[[3 1 2 3 1 2 3 1 2 3 1 2]]
r5 type: (1, 12)
r6 
[[3 1 2]
 [3 1 2]
 [3 1 2]
 [3 1 2]]


* 从后面往前面遍历元组(2,3)。先将a复制3次，然后将复制后的结果保存到a=[0, 1, 2, 0, 1, 2, 0, 1, 2]。
    再复制2次。得到目标数组。

In [14]:
a = np.array([0,1,2])
r = np.tile(a,(2,3))
print("r=\n",r)

r=
 [[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


* 从后面往前遍历元组(3,1)，先将a复制1次，然后将复制的结果保存到a。再复制3次。


In [ ]:
r=np.tile(a,(3,1))
print("r=\n",r)

### 数据类型转换

In [ ]:
m = np.array([[1.5,2.7,3.8],[2.4,6.2,7.9]])
h = m.astype(np.float)  # 用另一种类型表示
print('m=',m)
print('h=',h)

### 数据保存

In [15]:
p = np.array(  [[1, 2, 3, 4],    [5, 6, 7, 8]])
 
np.save('p.npy', p)     # 保存到文件
q = np.load('p.npy')    # 从文件读取
print('p=')
print(p)
print('q=')
print(q)

p=
[[1 2 3 4]
 [5 6 7 8]]
q=
[[1 2 3 4]
 [5 6 7 8]]


### 切片与子阵

In [16]:
m = np.arange(32)
m = np.reshape(m,(4,8))
print('m=')
print(m)
m1 = m[:,::-1] #类似matlab, fliplr--列颠倒放置得到的矩阵
print('m1=\n',m1)
m2= m[::-1,:] #类似matlab, flipud--列颠倒放置得到的矩阵
print('m2=\n',m2)

m=
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
m1=
 [[ 7  6  5  4  3  2  1  0]
 [15 14 13 12 11 10  9  8]
 [23 22 21 20 19 18 17 16]
 [31 30 29 28 27 26 25 24]]
m2=
 [[24 25 26 27 28 29 30 31]
 [16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7]]


## 数组的拼接

In [17]:

import numpy as np
l0 = np.arange(6).reshape((2, 3))
l1 = np.arange(6, 12).reshape((2, 3))
print(l0)
print(l1)

m1 = np.row_stack((l0, l1)) # 同vstack
m2 = np.column_stack((l0, l1)) # 同hstack
m3 = np.dstack((l0, l1)) # 
print('m1 row_stack:')
print(m1)
print('m2 column_stack:')
print(m2)
print('m3 dstack:')
print(m3)



[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
m1 row_stack:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
m2 column_stack:
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
m3 dstack:
[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


In [18]:
# vstack是指沿着纵轴拼接两个array, vertical
# hstack是指沿着横轴拼接两个array, horizontal
m1 = np.vstack((l0, l1))
m2 = np.hstack((l0, l1))
print('m1 vstack:')
print(m1)
print('m2 hstack:')
print(m2)
u1 = np.concatenate((l0,l1),axis=0)
u2 = np.concatenate((l0,l1),axis=1)
# 可以参考: https://www.cnblogs.com/shueixue/p/10953699.html
print('u1=')
print(u1)
print('u2=')
print(u2)
m3 = np.stack((l0, l1))
print('m3 stack:')
print(m3)
print(m3.shape)

m1 vstack:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
m2 hstack:
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
u1=
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
u2=
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
m3 stack:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Numpy中stack()，hstack()，vstack()函数详解
https://blog.csdn.net/csdn15698845876/article/details/73380803/


## 矩阵的变形

In [19]:
u=np.arange(6,12).reshape(2,3)
print('u=')
print(u)
t1 = np.rot90(u, 1)
t2 = np.fliplr(u)
t3 = np.flipud(u)
print('t1=');print(t1)
print('t2=');print(t2)
print('t3=');print(t3)

y = np.roll(u, 1)
print('y=');print(y)
print('y transpose'); print(y.transpose())

u=
[[ 6  7  8]
 [ 9 10 11]]
t1=
[[ 8 11]
 [ 7 10]
 [ 6  9]]
t2=
[[ 8  7  6]
 [11 10  9]]
t3=
[[ 9 10 11]
 [ 6  7  8]]
y=
[[11  6  7]
 [ 8  9 10]]
y transpose
[[11  8]
 [ 6  9]
 [ 7 10]]


## 矩阵的切分split

```text
1、split(ary, indices_or_sections, axis=0)
把一个数组从左到右按顺序切分 
参数： 
ary:要切分的数组 
indices_or_sections:如果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭） 
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
参考:https://blog.csdn.net/mingyuli/article/details/81227629
```


​

In [21]:
# x是一个行数组的情形
x = np.arange(9.0)
u1=np.split(x, 3) # 返回的是一个list对象
print('u1='); print(u1)
print(type(u1),type(u1[0]),type(u1[1]))


u1=
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]
<class 'list'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [22]:
# x是一个行数组的情形
x = np.arange(8.0)
u2 = np.split(x, [3, 5, 6, 10])
print('u2='); print(u2)

u2=
[array([0., 1., 2.]), array([3., 4.]), array([5.]), array([6., 7.]), array([], dtype=float64)]


In [ ]:
```python

```

    u2=
    [array([0., 1., 2.]), array([3., 4.]), array([5.]), array([6., 7.]), array([], dtype=float64)]


In [23]:
#（3，）的用法
# 参考: https://blog.csdn.net/mingyuli/article/details/81227629
m = np.arange(8.0)
t1 = np.split(m, (3,))
print('t1='); print(t1)
 
#结果：[array([0., 1., 2.]), array([3., 4., 5., 6., 7.])]
 
#机器学习中的用法解释：
#axis=1,代表列，是要把data数据集中的所有数据按第四、五列之间分割为X集和Y集。
x, y = np.split(m, (4,),axis=0) 
print('x='); print(x)
print('y='); print(y)

t1=
[array([0., 1., 2.]), array([3., 4., 5., 6., 7.])]
x=
[0. 1. 2. 3.]
y=
[4. 5. 6. 7.]


In [24]:
# Test 1
A = np.arange(12).reshape(3, 4)
print( A)
 
# 纵向分割, 分成两部分, 按列分割
m1 = np.split(A, 2, axis = 1) # 好像要均分才行.
# 横向分割, 分成三部分, 按行分割
m2 = np.split(A, 3, axis = 0)
print('m1='); print(m1)
print('m2='); print(m2)
print(type(m1),type(m2)) # 返回结果为list对象

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
m1=
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
m2=
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
<class 'list'> <class 'list'>


In [25]:
A = np.arange(12).reshape(3, 4)
print( A)
print('vsplit:')
print(np.vsplit(A, 3))
# 水平方向分割
print('hsplit:')
print( np.hsplit(A, 2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
vsplit:
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
hsplit:
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### array_split可以实现不均等划分

​

In [26]:
import numpy as np
x = np.arange(8.0)
print('array_split:'); print( np.array_split(x,3) )
# print('      split:'); print(np.split(x,3)) # 报错


array_split:
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]


​

In [ ]:
x = np.arange(24).reshape(6,4)
m = np.array_split(x,4)

print('source matrix:'); print(x)
print('array_split:'); print(m )
print(type(m))


​

In [7]:
x =np.random.randint(0,10,size=(3,5))
print(x)
u=x.sum(axis=0)
print(u)
m=np.mat(x)
u2=m.sum(axis=0)
print(u2)




[[9 0 3 4 6]
 [4 9 6 2 7]
 [5 0 9 4 0]]
[18  9 18 10 13]
[[18  9 18 10 13]]


## 矩阵运算

* 统计函数与数组运算类似.结果的维数还有些差异.

In [ ]:
# make matrix
g = np.matrix([[1,2,3],[5,5,6],[7,9,9]])
I = g*g**-1
print (I)

​

In [ ]:
d = np.mat([[3, 9,1,10], [7, 4,6,0],[8,3,5,9]])         # 二维numpy数组
r1 = d.sum(axis=0)
r2 = d.sum(axis=1)
print('d =')
print(d)
print('r1 shape ',r1.shape)
print('r2 shape ',r2.shape)
print('每列求和:')
print(r1)
print('每列求和:')
print(r2)





## 对numpy数组表示的数据进行标准化处理

* 请设计程序对numpy表示的二维数组进行标准化处理

编写示例程序完成计算

下面给出构造二维数组的代码。每列表示一个特征，每行表示一个样本。

​

In [ ]:
import numpy as np
a=np.fix(10*np.random.rand(4,5))
print('二维数组:')
print(a)



​

## Python用于科学计算的一些常用工具和库

* IPython-增强的交互环境：支持变量自动补全，自动缩进，支持 bash shell命令，内置了许多很有用的功能和函数
* Spyder、Wing IDE或Eclipse/Pydev：集成开发环境
* NumPy-数学计算基础库：N维数组、线性代数计算、傅立叶变换、随机数等。
* SciPy-数值计算库：线性代数、拟合与优化、插值、数值积分、稀疏矩阵、图像处理、统计等。
* SymPy-符号运算
* Pandas-数据分析库：数据导入、整理、处理、分析等。
* matplotlib-会图库：绘制二维图形和图表
* Chaco-交互式图表
* OpenCV-计算机视觉库
* TVTK-数据的三维可视化
* Cython-Python转C的编译器：编写高效运算扩展库的首选工具
* BioPython-生物科学

In [ ]:
%matplotlib inline
%pylab inline

In [ ]:
Populating the interactive namespace from numpy and matplotlib



In [ ]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

生成ndarray，即N-Dimensional Array Object，N维数组

* array
* matrix

In [ ]:
import numpy as np
A  = np.array([[2,3,4],[3,4,5]]) #标准创建方法
B  = np.array([[1,2,1],[2,3,4]])
print(A)
print(B)
C = A*B
print(C)
D = A/B
print(D)
"""类似功能由MATLAB实现:代码如下
A  = [[2,3,4];[3,4,5]]% 标准创建方法
B  = [[1,2,1];[2,3,4]]

C= A.*B
运行结果：
A =
     2     3     4
     3     4     5

B =
     1     2     1
     2     3     4


C =
     2     6     4
     6    12    20
"""


'类似功能由MATLAB实现:代码如下\nA  = [[2,3,4];[3,4,5]]% 标准创建方法\nB  = [[1,2,1];[2,3,4]]\n\nC= A.*B\n运行结果：\nA =\n     2     3     4\n     3     4     5\n\nB =\n     1     2     1\n     2     3     4\n\n\nC =\n     2     6     4\n     6    12    20\n'



In [ ]:
import numpy as np
A  = np.mat(np.array([[2,3,4],[3,4,5]]) )#标准创建方法
B  = np.mat(np.array([[1,2,1],[2,3,4]])).T # np.mat将array转为矩阵类型
print(A)
print(B)
C = A*B # 矩阵乘法 C为矩阵A与矩阵B之积
print(C)
"""类似的MATLAB代码:
A  = [[2,3,4];[3,4,5]]% 标准创建方法
B  = [[1,2,1];[2,3,4]]'

C= A*B
运行结果:
A =
     2     3     4
     3     4     5

B =
     1     2
     2     3
     1     4

C =
    12    29
    16    38
"""

## array的dot函数

In [ ]:
import numpy as np
A  = np.array([[2,3,4],[3,4,5]]) #标准创建方法
B  = np.array([[1,2,1],[2,3,4]]).T
print(A)
print(B)
C = np.dot(A,B)
print(C)

## matrix 做数组运算multiply

In [ ]:
import numpy as np
A  = np.mat(np.array([[2,3,4],[3,4,5]]) )# 标准创建方法
B  = np.mat(np.array([[1,2,1],[2,3,4]])) # np.mat将array转为矩阵类型
print(A)
print(B)
C = np.multiply(A,B) #
print(C)


In [ ]:
[[2 3 4]
 [3 4 5]]
[[1 2 1]
 [2 3 4]]
[[ 2  6  4]
 [ 6 12 20]]



In [ ]:
a = np.random.rand(3)
print(a)

b = np.random.rand(3,4)
print(b)


In [ ]:
[0.13080455 0.22781023 0.06283916]
[[0.00476745 0.52431212 0.66107212 0.59896762]
 [0.67285076 0.27069669 0.68191116 0.0882349 ]
 [0.36351147 0.09211691 0.05282372 0.01011045]]



In [ ]:
arr = np.arange(10).reshape(2,5) #arrange类似于range,但返回的是ndarray，算是快速创建方法，只能生成一维数组，多维需要reshape
arr

In [ ]:
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])




In [ ]:
np.array([[2,3,4],[3,4,5]]) #标准创建方法

In [ ]:
array([[2, 3, 4],
       [3, 4, 5]])




In [ ]:
np.asarray((1,2,3)) #将输入装换为ndarray

In [ ]:
array([1, 2, 3])




In [ ]:
np.arange(10,25,5)#类似内置的range，返回ndarray

In [ ]:
array([10, 15, 20])




In [ ]:
a = np.ones((2,2),dtype=np.int32)
print(a)
b = np.ones_like(arr) #根据指定的形状和dtype创建全1数组。ones_like以另一个数组作为形状参数
print(b)

In [ ]:
[[1 1]
 [1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]]



In [ ]:
a = np.eye(2)
print(a)
b = np.identity(3)#创建一个N*N的单位矩阵(对角线为1，其余为0)
print(b)

In [ ]:
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [ ]:
np.linspace(0,2,9)#创建等差数列,[0,2]中取9个数

In [ ]:
array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])



## 求矩阵的逆

In [ ]:
a = np.array([[1,2,3],[4,2,1],[2,1,2]])
ainv  = np.linalg.inv(a)
ainv2 = np.linalg.inv(np.mat(a))
print(ainv)
print(ainv2)

print(type(ainv),type(ainv2))


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a
a[0,1] = 9
print(a)
print(a[0:2,0:2]) # 获取子阵


In [ ]:
#ndarray里所有元素必须是相同类型，每个ndarray都有一个shape和一个dtype等

In [ ]:
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)

In [ ]:
#ndarray的数据类型是可以转换的
b = a.astype(np.float64)
print(b)

数组和标量之间的运算

In [ ]:
#数组与标量之间的运算会将运算应用到元素级
arr**2

In [ ]:
[1,2,3]*3 #普通的列表或是元组，只能与整数相乘，表示多个该数据合并

索引和切片

In [ ]:
arr[:,3:]=0
arr

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #ndarray的标准创建方法，
#arr3d的维度是2*2*3,,指2个两行三列的数组组成的数组，，A=a1*a2*....*a(n),,,a(n-1)代表行，a(n)代表列，A[0]代表从a1切片
arr3d[0]

In [ ]:
old_values = arr3d[0].copy() #使用copy是新生成了一个副本记录，一般的索引只是引用了原始数据的视图，改变视图即改变了原始数据
arr3d[0] = 42
arr3d

In [ ]:
arr3d[0] = old_values
arr3d

In [ ]:
crr=np.arange(9).reshape(3,3)
crr[1,:2],crr[1:2,:2] #注意这里的不同，前面是一维数组，后面是二维数组

In [ ]:
arr3d[1, 0]

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)    #布尔型索引特别注意，轴长应等于被索引的数组长度
data

In [ ]:
data[names == 'Bob']#这里是等于行数7

In [ ]:
mingzi = ['aa','bb','cc','bb'] ##
c = data[mingzi== 'bb']
print(c)
mingzi = np.array(['aa','bb','cc','bb'])##
c = data[:,mingzi== 'bb']
print(c)

In [ ]:
data[names == 'Bob']= 0 #布尔索引也是引用视图的形式
print('data:',data)
data[names=='Bob']=0
data[names != 'Joe'] = 7
print(data)

In [ ]:
import numpy as np #花式索引
arr = np.arange(32).reshape((8, 4))
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]=0
print(arr)

In [ ]:
arr[-3,-1]

In [ ]:
23




In [ ]:
arr[[-5]]

In [ ]:
array([[12, 13, 14, 15]])




In [ ]:
arr[-5]

In [ ]:
array([12, 13, 14, 15])




In [ ]:
arr[[-3, -5, -7]]

In [ ]:
arr[[-3, -5, -7]]=0

In [ ]:
arr

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr[[1,5,7,2]][:,[0,3,1,2]],arr[:,[0,3,1,2]][[1,5,7,2]] #先后顺序可变

In [ ]:
#总结一下：基本索引/切片、布尔索引、一级花式索引都是引用视图，，但是，花式索引中一次传入多个索引数组则会创建副本

## 数组转置和形状变化

In [ ]:
arr=np.arange(32).reshape(8,4)
arr

In [ ]:
brr=arr.reshape(2,16)  #看来，reshape也是引用视图
brr[1]=0
arr

In [ ]:
arr = np.arange(30).reshape((2,3, 5)) #2个3行5列ndarray组成的三维ndarray
arr

In [ ]:
arr.T#简单转置，变成了(5,3,2),,5个3行2列的ndarray

In [ ]:
arr.transpose((1, 0, 2))#高级转置，用元组表示转置的轴，第一个轴和第二个轴互换，shape是(3,2,5),费脑子,复制新数据

In [ ]:
arr.swapaxes(1, 2) #换第二个和第三个轴，引用视图

In [ ]:
arr.transpose((2, 1, 0))

In [ ]:
array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])




In [ ]:
arr.reshape(3,2,5) #reshape只是更改数据的形状，元素顺序不变，，换轴会导致元素顺序变化

In [ ]:
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])



## 元素级数组函数

In [ ]:
x = np.random.randn(8).reshape(2,4)
y = np.random.randn(8).reshape(2,4)
np.maximum(x, y) #取对应元素最大值
np.power(x,y),x**y,2**y
np.add(x,1)

In [ ]:
np.logical_not(x>0),-x>0 #两者等价

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
from matplotlib.pyplot import imshow, title
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

* 数组统计方法，一般是聚合计算，以数组或是某条轴作为参数

In [ ]:
arr = np.random.randn(5, 4)
arr

In [ ]:
t1 = arr.mean(0) #5行4列，在行上求均值，结果就是行榻缩成4个点
t2 = np.mean(arr,0)
print('t1',t1)
print('t2',t2)
print(arr.sum())
print(arr.mean(axis=1))#axis指计算该轴向上的统计值，结果是消灭该轴
print(arr.sum(0))#即axis=0

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [ ]:
arr.cumsum(0)

In [ ]:
array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)




In [ ]:
arr.cumprod(1)

In [ ]:
array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)




In [ ]:
arr = randn(100)
(arr > 0).sum() # 计算中布尔值会被自动转换为0或1

In [ ]:
45




In [ ]:
bools = np.array([False, False, True, False])

In [ ]:
bools.any()

In [ ]:
True




In [ ]:
bools.all()

In [ ]:
False



ndarry排序

In [ ]:
arr=randn(5,3)
arr

In [ ]:
array([[ 0.2244, -1.5502,  0.2917],
       [ 0.5305,  0.0684,  1.4814],
       [-0.138 ,  0.8196, -0.7189],
       [-0.9486, -0.0314, -0.9882],
       [-1.1357, -0.7062,  1.6862]])




In [ ]:
arr.sort()#默认是在axis=0上做排序

In [ ]:
arr#排序会创建副本，就地排序会修改数据

In [ ]:
array([[-1.5502,  0.2244,  0.2917],
       [ 0.0684,  0.5305,  1.4814],
       [-0.7189, -0.138 ,  0.8196],
       [-0.9882, -0.9486, -0.0314],
       [-1.1357, -0.7062,  1.6862]])




In [ ]:
initial_value = 0
sample_list = [initial_value for i in range(10)]

In [ ]:
sample_list

In [ ]:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]




In [ ]:
sample_list = [initial_value]*5
sample_list

In [ ]:
[0, 0, 0, 0, 0]




In [ ]:
[1,2,3]*5,(1,2,3)*5  #这是列表和元组同数值相乘

In [ ]:
arr=np.array([1,2,3]) #这是ndarray与数值相乘,实际是里面的元素同数值相乘
arr*5

In [ ]:
k=[]
for i  in [1,2,3]:
    k.append(i*5)
k

In [ ]:
import this  #Python之歌

数组函数where，表述条件逻辑

In [ ]:
# 演示np.where的用法
import numpy as np
a = np.fix(10*np.random.rand(5,4))
print(a)
# 获取a中小于5的元素个数
c = np.where(a<5)
print(c)
print(type(c))
print('row index:',c[0])
print('col index:',c[1])
print('col index size:',c[1].size) # 元素个数
# 请将a中小于5的元素置为9
d1 = a.copy()
d2 = a.copy()
d1[np.where(d1<5)] = 9
print(d1)

d2[d2 < 5] = 9 # 更简洁
print(d2)


In [ ]:
[[7. 8. 1. 5.]
 [6. 8. 4. 5.]
 [6. 9. 5. 4.]
 [2. 0. 4. 8.]
 [7. 5. 1. 3.]]
(array([0, 1, 2, 3, 3, 3, 4, 4], dtype=int64), array([2, 2, 3, 0, 1, 2, 2, 3], dtype=int64))
<class 'tuple'>
row index: [0 1 2 3 3 3 4 4]
col index: [2 2 3 0 1 2 2 3]
col index size: 8
[[7. 8. 9. 5.]
 [6. 8. 9. 5.]
 [6. 9. 5. 9.]
 [9. 9. 9. 8.]
 [7. 5. 9. 9.]]
[[7. 8. 9. 5.]
 [6. 8. 9. 5.]
 [6. 9. 5. 9.]
 [9. 9. 9. 8.]
 [7. 5. 9. 9.]]



In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

In [ ]:
result

In [ ]:
result = np.where(cond, xarr, yarr)#条件判断神器where
result

In [ ]:
arr = np.random.randn(4, 4)
arr
np.where(arr > 0, 2, -2)

In [ ]:
T=np.where(arr>0,2,arr)
print(T)

In [ ]:
cond1=[True, False, True, True, False]
cond2=[True, True, True, False, False]
result = []
for i in range(5):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
result        

In [ ]:
np.where(cond1 and cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
0&1 #&和|不能用于两个列表

### 统计聚合函数

In [ ]:
arr = np.random.randn(5, 4)
arr

In [ ]:
arr.sum()

In [ ]:
arr.argmin() #最小元素的索引，第9个

In [ ]:
8




In [ ]:
np.argmin(arr) #第二种引用方法

In [ ]:
arr.cumsum()  #累加

In [ ]:
arr.cumsum(0) #以行为基础，在列上累加

In [ ]:
arr.cumsum(1)

Unique函数

In [ ]:
names = np.array(['Bob', 'Zoe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
np.unique(names) #unique函数同集合的操作类似，数据结果会自动排序

In [ ]:
array(['Bob', 'Joe', 'Will', 'Zoe'], 
      dtype='<U4')




In [ ]:
sorted(set(names))

In [ ]:
['Bob', 'Joe', 'Will', 'Zoe']



数据存取（文本文件或二进制文件）

In [ ]:
arr=np.arange(10).reshape(2,5)

In [ ]:
np.save('some_array',arr) #存在当前路径下，二进制格式

In [ ]:
np.load('some_array.npy') #记得带上n(女)p(朋)y(友)

In [ ]:
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])




In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)#将多个数组保存为一个压缩文件

In [ ]:
np.load('array_archive.npz') 

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
arr = np.loadtxt('ch04/array_ex.txt', delimiter=',')
arr[:3]

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [ ]:
x.dot(y)  #dot,矩阵乘法，，2行3列 * 3行2列，得出2行2列的结果

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr   #linalg矩阵分解运算包

In [ ]:
X = randn(5, 5)

In [ ]:
X

In [ ]:
mat = X.T.dot(X)

In [ ]:
mat

In [ ]:
X.dot(X.T)

In [ ]:
inv(mat)

### numpy里的随机函数

In [ ]:
samples = np.random.normal(size=(4, 4)) #normal生成标准正态分布
samples

In [ ]:
from random import normalvariate

In [ ]:
N=1000000

In [ ]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

In [ ]:
%timeit np.random.normal(size=N) #numpy里的随机函数快很多

### 模拟随机漫步

In [ ]:
from random import random,randint    #random自带的随机整数调用方法
from pylab import *

In [ ]:
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step=1 if randint(0, 2) else -1
    position+=step
    walk.append(position)

In [ ]:
plot(walk)

​    

​

In [ ]:
np.random.seed(12345)

In [ ]:
draws = np.random.randint(0, 2, size=20) 
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk

In [ ]:
walk.max()

In [ ]:
draws = np.random.randint(0, 2, size=(20,30))
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum(1)

In [ ]:
walk

In [ ]:
#继续探索random模块

In [ ]:
np.random.seed(12345)

In [ ]:
np.random.randn(4,4)

In [ ]:
array([[ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608],
       [-0.8608,  0.5601, -1.2659,  0.1198],
       [-1.0635,  0.3329, -2.3594, -0.1995]])
np.random.randint(0,2,(3,3)) #生成一个3行3列的随机整数数组，范围是[0,2)
np.random.choice(5, 3)#在[0,5)里随机选取整数，选3次，，等价于randint(0,5,3)
np.random.choice(5, 3, p=[0.1, 0, 0.1, 0.1, 0.7])#p指定每个整数在一次选取中出现的概率，长度应与整数值对应


In [ ]:
np.random.choice(5, 4, replace=False)#该参数表示出现的数据不重复，，那么数组长度应小于整数值，相当于np.random.permutation(np.arange(5))[:4]
np.random.permutation(5)[:4]
arr=np.array(['a','b','c','d'])
print(arr)
np.random.choice(arr,(2,2),p=[0.1,0.7,0.2,0])#arr只能是一维数组

In [6]:
import numpy as np
print(np.random.permutation(5))
print(np.random.randn(4,2))
print(np.random.normal(size=(4,2)))#同上
print(np.random.binomial(10, 0.4, size=10))#二项分布，发生事件的概率为p,n次独立试验中成功的次数为结果
t=np.random.uniform(0, 1,size=5)#均匀分布
np.random.chisquare(3,6)#卡方分布，前面是自由度，后面是size

[4 3 2 1 0]
[[ 0.252978   -1.24609735]
 [ 0.31283101  0.25609939]
 [-0.37739239 -1.92641729]
 [-0.65449801 -0.29887275]]
[[ 1.0657003   1.29719586]
 [-0.24453192 -0.17947344]
 [ 1.4074108   0.63988504]
 [-1.0612907   1.08148786]]
[5 3 3 4 6 3 4 3 4 3]


array([0.67900653, 4.36583538, 0.44890802, 4.30041622, 2.95014141,
       1.82053643])

## 筛选元素

In [ ]:
import numpy as np
a = np.fix(10*np.random.rand(1,8))
print(a)
c = (a>=2) & (a<=5)
print('c:')
print(c)

In [ ]:
t1=np.where((a>=2) & (a<=5))
t2=np.nonzero((a>=2) & (a<=5))
print(t1)
print(type(t1))
print(t2)
print(type(t2))

(a[t1]==a[t2]).all()
print(a)

In [ ]:
idx = np.nonzero(a>6)
print(idx)
t=(a>=2) & (a<=3)
print(t)

In [ ]:
import numpy as np
a = np.random.rand(3,5)
print(a)
u = np.mat(a)
print('type:',type(u.A))
print(u.A)
print(u)
print(type(u))
print(type(u.A))

* Python-Numpy中array和matrix的用法

https://blog.csdn.net/u010712012/article/details/82817208