In [14]:
import numpy as np
A = np.mat(np.fix(100*np.random.rand(6,5)))
A_max = A.max(axis=0)
A_min = A.min(axis=0)
A_ave = A.mean(axis=0)
A_sum = A.sum(axis=0)
A_max2 = A.max(axis=1)
A_min2 = A.min(axis=1)
A_ave2 = A.mean(axis=1)
A_sum2 = A.sum(axis=1)
d = {'Amax':A_max,'Amin':A_min,'Aave':A_ave,'Asum':A_sum}
d2 = {'Amax':A_max2,'Amin':A_min2,'Aave':A_ave2,'Asum':A_sum2}
print(A)
print(type(A))
print('按列')
print(d)
print('按行')
print(d2)

[[46. 75. 10. 68. 82.]
 [63. 91. 82. 59. 31.]
 [74. 11. 88. 23. 61.]
 [66. 14. 55. 40.  1.]
 [42. 61. 65. 78. 68.]
 [ 6. 51. 30. 12.  7.]]
<class 'numpy.matrix'>
按列
{'Amax': matrix([[74., 91., 88., 78., 82.]]), 'Amin': matrix([[ 6., 11., 10., 12.,  1.]]), 'Aave': matrix([[49.5       , 50.5       , 55.        , 46.66666667, 41.66666667]]), 'Asum': matrix([[297., 303., 330., 280., 250.]])}
按行
{'Amax': matrix([[82.],
        [91.],
        [88.],
        [66.],
        [78.],
        [51.]]), 'Amin': matrix([[10.],
        [31.],
        [11.],
        [ 1.],
        [42.],
        [ 6.]]), 'Aave': matrix([[56.2],
        [65.2],
        [51.4],
        [35.2],
        [62.8],
        [21.2]]), 'Asum': matrix([[281.],
        [326.],
        [257.],
        [176.],
        [314.],
        [106.]])}


In [16]:
import numpy as np
a = np.fix(100*np.random.rand(1,10))

print(a)

[[93. 93. 21. 23. 71.  0. 19. 93. 72. 61.]]
